# Generated by Django 4.2.1 on 2024-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reachout",
            name="message",
            field=models.TextField(
                help_text="Remember to rate the recipe before leaving a comment"
            ),
        ),
    ]
