# Generated by Django 4.2.1 on 2024-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_reachout_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reachout",
            name="message",
            field=models.TextField(),
        ),
    ]
