# Generated by Django 4.2.1 on 2024-04-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_contactme"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMe",
            new_name="Contact",
        ),
    ]
