# Generated by Django 4.2.1 on 2024-04-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_reachout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReachOut",
        ),
    ]
