# Generated by Django 4.2.1 on 2024-03-25 12:42

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "servings",
                    models.IntegerField(
                        help_text="Please enter the number of portions that result from your recipe."
                    ),
                ),
                (
                    "cooking_duration",
                    models.IntegerField(
                        help_text="Please enter how many minutes is required for the preparation of your recipe"
                    ),
                ),
                ("ingredients", models.TextField()),
                ("preparation", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")], default=0
                    ),
                ),
                (
                    "approval_status",
                    models.IntegerField(
                        choices=[
                            ("0", "Pending Approval"),
                            ("1", "Approved"),
                            ("2", "Rejected"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "recipe_image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipe_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stars",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipe_stars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
