# Generated by Django 4.2.1 on 2024-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="stars",
        ),
        migrations.AddField(
            model_name="recipe",
            name="stars",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
