# Generated by Django 4.2.1 on 2024-03-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_stars_recipe_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="approval_status",
        ),
    ]
