# Generated by Django 4.2.1 on 2024-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_approval_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="stars",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "Popular Pancakes"),
                    (1, "Healthy Pancakes for Kids"),
                    (3, "Vegan Pancakes"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation",
            field=models.JSONField(),
        ),
    ]
