# Generated by Django 4.2.1 on 2024-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_options_remove_recipe_stars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation",
            field=models.TextField(),
        ),
    ]
