# Generated by Django 4.2.1 on 2024-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_remove_recipe_category_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "Popular Pancakes"),
                    (1, "Healthy Pancakes for Kids"),
                    (3, "Vegan Pancakes"),
                ],
                default=0,
            ),
        ),
    ]
