# Generated by Django 4.2.1 on 2024-03-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_remove_recipe_tags_recipe_category"),
        ("recipes", "0008_auto_20240325_1524"),
    ]

    operations = []
