# Generated by Django 4.2.1 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_merge_20240325_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation",
            field=models.JSONField(),
        ),
    ]
