# Generated by Django 4.2.1 on 2024-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "Popular Pancakes"),
                    (1, "Healthy Pancakes for Kids"),
                    (2, "Vegan Pancakes"),
                ],
                default=0,
            ),
        ),
    ]
