# Generated by Django 4.2.1 on 2024-04-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_recipe_ingredients_alter_recipe_preparation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="recipe_post",
            new_name="recipe",
        ),
    ]
