# Generated by Django 4.2.1 on 2024-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_recipe_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="number_of_ratings",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
