# Generated by Django 4.2.1 on 2024-04-07 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0017_savedrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="saved_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
