# Generated by Django 4.2.1 on 2024-04-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_alter_recipe_managers_alter_recipe_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="saved_recipes",
            new_name="saved",
        ),
    ]
