# Generated by Django 4.2.1 on 2024-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_rename_saved_recipes_recipe_saved"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedRecipe",
        ),
    ]
