# Generated by Django 4.2.1 on 2024-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_delete_savedrecipe"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="recipe",
            managers=[],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
    ]
