# Generated by Django 4.2.1 on 2024-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0022_alter_recipe_managers_alter_recipe_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
