# Generated by Django 4.2.1 on 2024-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0023_recipe_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "Popular Pancakes"),
                    (1, "Pancakes for Kids"),
                    (2, "Vegan Pancakes"),
                ],
                default=0,
            ),
        ),
    ]
