# Generated by Django 4.2.1 on 2024-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0024_alter_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="publish",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to allow your recipe to be published online.",
            ),
        ),
    ]
