# Generated by Django 4.2.1 on 2024-04-10 10:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0025_recipe_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
    ]
