# Generated by Django 4.2.1 on 2024-04-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0026_alter_recipe_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="publish",
            new_name="make_public",
        ),
    ]
