# Generated by Django 4.2.1 on 2024-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0031_alter_recipe_preparation"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="saved_boolean",
            field=models.BooleanField(default=False),
        ),
    ]
