# Generated by Django 4.2.1 on 2024-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0032_recipe_saved_boolean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="saved_boolean",
            field=models.BooleanField(default=True),
        ),
    ]
