# Generated by Django 4.2.1 on 2024-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0034_alter_recipe_saved_boolean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="Remember to rate the recipe before leaving a comment"
            ),
        ),
    ]
