# Generated by Django 4.2.1 on 2024-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0035_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="Remember to also rate the recipe before submitting a comment"
            ),
        ),
    ]
