# Generated by Django 4.2.1 on 2024-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0037_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation",
            field=models.TextField(),
        ),
    ]
