# Generated by Django 4.2.1 on 2024-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0039_alter_recipe_number_of_ratings_alter_recipe_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="number_of_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
