# Generated by Django 4.2.1 on 2024-07-03 13:18

import cloudinary.models
from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0040_alter_recipe_number_of_ratings_alter_recipe_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="Remember to also rate the recipebefore submitting a comment."
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_duration",
            field=models.IntegerField(
                help_text="Please enter how many minutes is required forthe preparation of your recipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder",
                max_length=255,
                validators=[
                    recipes.models.CustomFileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(
                help_text="Please enter the number of portions that resultfrom your recipe."
            ),
        ),
    ]