# Generated by Django 4.2.1 on 2024-07-05 08:51

import cloudinary.models
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0041_alter_comment_content_alter_recipe_cooking_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/dpxwugk91/image/upload/v1714425166/ufutddsehjdq8vjbtefx.webp",
                max_length=255,
                validators=[
                    recipes.models.CustomFileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
