# Generated by Django 4.2.1 on 2024-07-05 09:23

import cloudinary.models
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0042_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder",
                max_length=255,
                validators=[
                    recipes.models.CustomFileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
