# Generated by Django 4.2.1 on 2024-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0050_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="saved_boolean",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="make_public",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to allow your recipe tobe published online.",
            ),
        ),
    ]
