# Generated by Django 4.2.1 on 2024-09-06 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0054_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_duration",
            field=models.IntegerField(
                help_text="Please enter how many minutes is required forthe preparation of your recipe",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
