# Generated by Django 4.2.1 on 2024-09-06 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0055_alter_recipe_cooking_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(
                help_text="Please enter the number of portions that resultfrom your recipe.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
