# Generated by Django 4.2.1 on 2024-09-18 12:13

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0066_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
