# Generated by Django 4.2.1 on 2024-09-19 12:40

import cloudinary.models
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0079_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, validators=[recipes.models.file_validation]
            ),
        ),
    ]
